### PR TITLE
Refactoring the way to read maps

### PR DESCRIPTION
**Pull request by pacome35220**
# SORRY TO BROKE THE RECORD FOR THE BIGGEST PR
- add library functions
- remove unused files
- remove map_gen/ with rust file
- rename structures
- simplify the ways of doing many things

### As you can see below, there are many many more deletions than additions.

### CODE REVIEW

**Comment by pacome35220** [comment]
In centered_map() function, I left a if that seems to cause performance regressions, but it's not, because execution on xterm is working (cool).
Before this, there was many segmentation fault and valgrind error (array manipulation with negative index is not a good idea), but it was faster (why ? I'm not an ncurses expert sorry).

Can you tell me why your calculations are sometimes negative ?

**Comment by rudreais** [comment]
could you please show me an example of the negative value you're speaking of ? i can't seem to see where it occurs. and yes, many deletions, many from the rust generators and the config files, so no big deal.
also please, could you remove `my_strcat.c` file ? i'm way more confident in `strcat` function from libC if you understand.
```c
 	new[i] = create_map(my_strcat("./maps/", filename)); 
```
seems off to me. you're giving "./maps/" in your strcat function, but this function takes 2 char pointers.
here, you're sending a char array ("./maps/"), but it's an undefined behavior to modify a string literal. mind explaining it ?

**Comment by pacome35220** [comment]
Unlike `strcat` from libC, `my_strcat` create a new string which will receive the first and the second string. Memory for the new string is obtained with **malloc**(3), and will be freed with **free**(3).

**Comment by pacome35220** [comment]
For the negative value in centered_map(), just run the program and see that wprintf debug is called many time : particularly at the very beginning.

**Comment by rudreais** [comment]
the value is never below -1. it's caused due to terminal-size. 
my fix after the merge was to use ternary

**Pull request merged**
